version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: '09:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried
  - package-ecosystem: github-actions
    directory: actions/bundle-name
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: '09:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried
  - package-ecosystem: github-actions
    directory: actions/generate-cross-compilation-sdk
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: '09:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried
  - package-ecosystem: github-actions
    directory: actions/setup
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: '09:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried
