name: Add SDK assets to release

on:
  release:
    types:
      - published

jobs:
  build-sdk:
    strategy:
      matrix:
        host-os:
          - 'macos'
        host-os-version:
          - '13'
        host-arch:
          - 'x86_64'
          - 'arm64'
        target-arch:
          - 'x86_64'
          - 'arm64'
        target-os:
          - 'ubuntu'
        target-os-version:
          - '22.04'
    runs-on: ${{ matrix.host-os }}-${{ matrix.host-os-version }}
    steps:
      - uses: ffried/swift-cross-compilation-sdk/.github/actions/generate-cross-compilation-sdk@main
        id: generate-sdk
        with:
          host-os: ${{ matrix.host-os }}
          host-os-version: ${{ matrix.host-os-version }}
          host-arch: ${{ matrix.host-arch }}
          target-os: ${{ matrix.target-os }}
          target-os-version: ${{ matrix.target-os-version }}
          target-arch: ${{ matrix.target-arch }}
      - name: Upload asset
        env:
          RELEASE_NAME: ${{ github.ref_name }}
          ASSET_PATH: ${{ steps.generate-sdk.outputs.bundle-package-path }}
          ASSET_NAME: ${{ steps.generate-sdk.outputs.bundle-name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber "${RELEASE_NAME}" "${ASSET_PATH}#${ASSET_NAME}"
